name: Rebootly
version: '${project.version}'
main: hammynl.rebootly.Rebootly
api-version: 1.13
authors: [ Hammynl ]
description: Rebootly is a Minecraft plugin which makes your server restart automatically with some extra features.
commands:
  rebootly:
    description: "Shows the help page"
    usage: "Incorrect usage! use '/rebootly' to find out the correct syntax!"


